version: 2.1

jobs:
  test-python:
    docker:
      - image: cimg/python:3.13

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: python -m pip install -e ".[dev]"

      - run:
          name: Run pre-commit checks
          command: pre-commit run --all-files

      - run:
          name: Run Pyright
          command: pre-commit run pyright --all-files --hook-stage manual

      - run:
          name: Run tests
          command: pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')

      - store_test_results:
          path: junit.xml

workflows:
  build-and-test:
    jobs:
      - test-python
